window.addEventListener("load",()=>{setTimeout(()=>document.getElementById("loader").classList.add("hide"),500)});
function sendBudget(){const service=document.getElementById("service").value;const name=document.getElementById("clientName").value.trim();const phone=document.getElementById("clientPhone").value.trim();const note=document.getElementById("clientNote").value.trim();let message="Olá, Engenheiro Christian! Vim pelo portal digital da Renderização e gostaria de solicitar um orçamento.";message+="%0A%0AServiço de interesse: "+encodeURIComponent(service);if(name){message+="%0ANome/empresa: "+encodeURIComponent(name)}if(phone){message+="%0ATelefone: "+encodeURIComponent(phone)}if(note){message+="%0ADescrição: "+encodeURIComponent(note)}window.open("https://wa.me/5542999060610?text="+message,"_blank")}
function selectService(service){document.getElementById("service").value=service;document.getElementById("orcamento").scrollIntoView({behavior:"smooth"});}
function filterServices(){const input=document.getElementById("serviceSearch").value.toLowerCase();document.querySelectorAll("#serviceList button").forEach(btn=>{btn.style.display=btn.textContent.toLowerCase().includes(input)?"block":"none"})}
function sharePortal(){const data={title:"Renderização Serviços de Engenharia",text:"Portal digital da Renderização Serviços de Engenharia",url:window.location.href};if(navigator.share){navigator.share(data)}else{navigator.clipboard.writeText(window.location.href);alert("Link copiado!")}}
function openModal(title){document.getElementById("modalTitle").textContent=title;document.getElementById("modal").classList.add("show")}
function closeModal(){document.getElementById("modal").classList.remove("show")}
const observer=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible")}})},{threshold:.12});
document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));document.querySelectorAll("[data-count]").forEach(el=>{let target=parseInt(el.dataset.count);let current=0;let step=Math.max(1,Math.floor(target/45));let timer=setInterval(()=>{current+=step;if(current>=target){current=target;clearInterval(timer)}el.textContent=current+"+"},30)});let index=0;setInterval(()=>{const items=document.querySelectorAll(".testimonial");if(items.length){items[index].classList.remove("active");index=(index+1)%items.length;items[index].classList.add("active")}},3500)});
